[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "JBTvPecuG2GQTShKFVk48dq3pPMpeLAURmQXuw8Rm4os"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/theanh098/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
