[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "58PaLbpXsJbiNdJhebM1Prx2o9XecQ9ftXvwrJ8Q2BsL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/theanh098/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
